import type { Metadata } from "next";
import {   Cairo } from "next/font/google";
import "./globals.css";


const geistMono = Cairo({
  variable: "--font-geist-mono",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={` ${geistMono.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
